### ISSUE TITLE
تحدي مجموع مربع اﻷعداد

### ISSUE THREAD

**Issue by AbdallahEssamGaber** [ebrahimMaher/dalilmobarmg#7]
[في هذا التحدي](https://www.dalilmobarmg.com/tutorials/algorithms/intermediate/challenges#%D8%AA%D8%AD%D8%AF%D9%8A-%D9%85%D8%AC%D9%85%D9%88%D8%B9-%D9%85%D8%B1%D8%A8%D8%B9-%D8%A7%EF%BB%B7%D8%B9%D8%AF%D8%A7%D8%AF)

كتبت الكود صحيح وبأكثر من طريقة ولكن لازال يعطي لي الإجابة خاطئة 
هذا واحد من الكودات إلي أنا شغالة
```
function sumSquare(numbers){
  // dalilmobarmg.com challenge
  // Start Here

	var final = 0;
	for(var i = 0; i < 3; i++)
    {
			 final = (numbers[i] * numbers[i]) + final;
    }
		console.log(final);
}
sumSquare([2, 2, 3]);
```

**Comment by ebrahimMaher** [comment]
اعمل return بدلاً من console.log 
الدالة يجب أن تقوم بإرجاع قيمة الناتج وليس طباعته

**Comment by AbdallahEssamGaber** [comment]
اسف إني موضحتش باالشكل الكافي بس أنا قلت إني جربت أكتر من كود منهم ال return

```js
function sumSquare(numbers){
  // dalilmobarmg.com challenge
  // Start Here

	var final = 0;
	for(var i = 0; i < 3; i++)
    {
			 final = (numbers[i] * numbers[i]) + final;
    }
  return final;
}
sumSquare([2, 2, 3]);
```

ومش شغال

**Comment by ebrahimMaher** [comment]
الخطأ بسيط، الحلقة التكرارية تتكرر 3 مرات فقط، أي ستعمل الدالة فقط مع المصفوفات التي تحتوي على 3 أعداد، لكن لنفرض أن لدينا مصفوفة تحتوي على 5 أعداد مثلاً؟ لن تعمل ﻷن شرط الحلقة:
`i < 3`
 ولذلك يجب تغيير الشرط إلى: 
 `i < numbers.length`
 بحيث يتكرر عدد مرات يساوي عدد عناصر المصفوفة.
